### ISSUE TITLE
Condensed Weather not properly launching

### ISSUE THREAD

**Issue by IAmHugh001** [Zren/plasma-applet-condensedweather#11]
I just installed CachyOS a Arch based distro and when I attempt to run Condensed Weather after installing it I get the below. I have Big Linux, Garuda, Manjaro, and Xerolinux installed and Condensed Weather works perfectly fine in them. I've never had any issue with it in the past either. Any idea what is going on? Thanks

file:///home/locutus/.local/share/plasma/plasmoids/com.github.zren.condensedweather/contents/ui/main.qml:12:2: Type LibWeather.WeatherData unavailable

file:///home/locutus/.local/share/plasma/plasmoids/com.github.zren.condensedweather/contents/ui/libweather/WeatherData.qml:10:1: module "org.kde.plasma.private.weather" is not installed

**Comment by Locutus64** [comment]
`file:///home/locutus/.local/share/plasma/plasmoids/com.github.zren.condensedweather/contents/ui/main.qml:12:2: Type LibWeather.WeatherData unavailable

file:///home/locutus/.local/share/plasma/plasmoids/com.github.zren.condensedweather/contents/ui/libweather/WeatherData.qml:10:1: module "org.kde.plasma.private.weather" is not installed`

**Comment by Zren** [comment]
In the widget's description on the KDE Store:

> Uses the default KDE weather widget's data sources. Needs (sudo apt install plasma-widgets-addons) if you don't already have the default KDE weather widget installed.
