### ISSUE TITLE
Diferent display depending on source.

### ISSUE THREAD

**Issue by bjwest** [Zren/plasma-applet-condensedweather#8]
I get different displays when parsing data from wetter.com vs NOAA.  Wetter.com doesn't display the current temperature or humidity.  NOAA's data doesn't update on set interval or via refresh option in menu, and I've had NOAA's data remain the same for days.

Note: Both screenshots were taken around 2:30pm.  The data from NOAA is displaying an updated at time of 12:56, but at 12:56 it was in the 40's.

NOAA data:
![Screenshot_NOAA](https://user-images.githubusercontent.com/1934590/108773225-a5267c00-7523-11eb-8fac-4d92bca90feb.png)

wetter.com data: 
![Screenshot_wetter com](https://user-images.githubusercontent.com/1934590/108773243-a8ba0300-7523-11eb-8c96-03fec4eaf380.png)

**Comment by Zren** [comment]
Well different data sources provide different data.

### NOAA
* https://invent.kde.org/plasma/plasma-workspace/-/blob/master/dataengines/weather/ions/noaa/ion_noaa.cpp
* NOAA's raw station data is https://w1.weather.gov/xml/current_obs/index.xml
```xml
<station>
	<station_id>KJRB</station_id>
	<state>NY</state>
	<station_name>New York Downtown Manhattan</station_name>
	<latitude>40.7012</latitude>
	<longitude>-74.009</longitude>
	<html_url>http://w1.weather.gov/data/obhistory/KJRB.html</html_url>
	<rss_url>http://weather.gov/xml/current_obs/KJRB.rss</rss_url>
	<xml_url>http://weather.gov/xml/current_obs/KJRB.xml</xml_url>
</station>
```
* It grabs the lattitude and longitude and plunks it into this url:
* New York: https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdBrowserClientByDay.php?lat=40.7012&lon=-74.009&format=24+hourly&numDays=7

Can you confirm that the raw data is changing in your city? I need to confirm that it is the widget freezing and not updating.

**Comment by bjwest** [comment]
I'm not sure what you mean by confirm the raw data is changing for my city.  Of course it changes.  I highly doubt NOAA would  not update the data.  Anyway, this has been an ongoing problem with all KDE weather applets since 4.0 or so and I'm just tired of it.  I love the look of your plasmoid so I'm going to grab the source and see if I can figure out how to make my own backend and use my own API key to pull the data.

Also, now that I look at it, the screenshots on the KDE store page shows wettercom to look just like what I have, so I'm not sure it's really a problem, it's just there's no current temperature displayed which I find strange.

Nothing against your plasmoid, it's just the broken KDE weather widget you're using to pull the data.  I understand that parsing weather data can cost money after a number of requests so that's why you use the KDE wether applets to pull the data.  That has never worked for me, so that's why I'm going with using my own API key.

For what it's worth, the NOAA data still looks the same as above now as it did nine hours ago and I've removed the applet, reinstalled and reconfigured multiple times.

Thank you for getting back to me so quickly.
